name: aws-ps-s3-plugin
version: 1.0.0
rundeckPluginVersion: 1.2
author: Rundeck
date: Tue Dic 12 2017
providers:
  - name: aws-ps-s3-cp-step
    service: RemoteScriptNodeStep
    title: 'PS / aws / s3 / cp'
    description: 'Copies a local file or S3 object to another location locally or in S3.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-cp.ps1
    script-args: -source '${config.source}' -destination '${config.destination}' -search_pattern '${config.search_pattern}' -recursive '${config.recursive}' -endpoint_url ${config.endpoint_url} -access_key ${config.access_key} -secret_access_key ${config.secret_access_key} -default_region ${config.default_region}
    config:
      - type: String
        name: source
        title: source
        description: 'the S3 URI or local path'
      - type: String
        name: destination
        title: destination
        description: 'the S3 URI or local path'
      - type: String
        name: search_pattern
        title: Search Pattern
        description: 'Just copy files (local path) that match the specified pattern.'  
      - type: Boolean
        name: recursive
        title: recursive
        description: 'Use --recursive?'
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: Default region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection
  - name: aws-ps-s3-mv-step
    service: RemoteScriptNodeStep
    title: 'PS / aws / s3 / mv'
    description: 'Moves a local file or S3 object to another location locally or in S3.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-mv.ps1
    script-args: -source '${config.source}' -destination '${config.destination}' -search_pattern '${config.search_pattern}' -recursive '${config.recursive}' -endpoint_url ${config.endpoint_url} -access_key ${config.access_key} -secret_access_key ${config.secret_access_key} -default_region ${config.default_region}
    config:
      - type: String
        name: source
        title: source
        description: 'the S3 URI or local path'
      - type: String
        name: destination
        title: destination
        description: 'the S3 URI or local path'
      - type: String
        name: search_pattern
        title: Search Pattern
        description: 'Just copy files (local path) that match the specified pattern.'  
      - type: Boolean
        name: recursive
        title: recursive
        description: 'Use --recursive?'
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection          
  - name: aws-ps-s3-sync-step
    service: RemoteScriptNodeStep
    title: 'PS / aws / s3 / sync'
    description: 'Syncs directories and S3 prefixes.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-sync.ps1
    script-args: -source '${config.source}' -destination '${config.destination}' -remove ${config.remove} -endpoint_url ${config.endpoint_url} -access_key ${config.access_key} -secret_access_key ${config.secret_access_key} -default_region ${config.default_region}
    config:
      - type: String
        name: source
        title: source
        description: 'the S3 URI or local path'
      - type: String
        name: destination
        title: destination
        description: 'the S3 URI or local path'
      - type: Boolean
        name: remove
        title: Delete
        description: 'Delete destination files that dont exists on source'
        default: false
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection
  - name: aws-ps-s3-ls-step
    service: WorkflowNodeStep
    title: 'PS / aws / s3 / ls'
    description: 'List S3 objects and common prefixes under a prefix or all S3 buckets.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-ls.ps1
    script-args: ${config.access_key} ${config.secret_access_key} ${config.S3Uri}
    config:
      - type: String
        name: S3Uri
        title: S3Uri
        description: 'the S3 URI'
      - type: Boolean
        name: human-readable
        title: human-readable
        description: 'Use --human-readable? Displays file sizes in human readable format.'
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection
  - name: aws-ps-s3-rm-step
    service: WorkflowNodeStep
    title: 'PS / aws / s3 / rm'
    description: 'Deletes an S3 object.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-rm.ps1
    script-args: ${config.access_key} ${config.secret_access_key}
    config:
      - type: String
        name: S3Uri
        title: S3Uri
        description: 'the S3 URI'    
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection          
  - name: aws-ps-s3-mb-step
    service: WorkflowNodeStep
    title: 'PS / aws / s3 / mb'
    description: 'Creates an S3 bucket.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-mb.ps1
    script-args: ${config.access_key} ${config.secret_access_key} ${config.S3Uri}
    config:
      - type: String
        name: S3Uri
        title: S3Uri
        description: 'the S3 URI'
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection
  - name: aws-ps-s3-rb-step
    service: WorkflowNodeStep
    title: 'PS / aws / s3 / rb'
    description: 'Deletes an empty S3 bucket.'
    plugin-type: script
    script-interpreter: powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command
    script-file: s3-rb.ps1
    script-args: ${config.access_key} ${config.secret_access_key} ${config.S3Uri}
    config:
      - type: String
        name: S3Uri
        title: S3Uri
        description: 'the S3 URI'
      - type: Boolean
        name: force
        title: force
        description: 'Use --force? Deletes all objects in the bucket including the bucket itself.'
      - type: String
        name: endpoint_url
        title: Endpoint URL
        renderingOptions:
          grouping: secondary
          groupName: Connection        
      - type: String
        name: access_key
        title: access_key
        description: 'Access Key ID'
        renderingOptions:
          grouping: secondary
          groupName: Connection
      - type: String
        name: secret_access_key
        title: secret_access_key
        description: 'Secret access Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: default_region
        title: default_region
        description: 'The default AWS region'
        renderingOptions:
          grouping: secondary
          groupName: Connection